### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Alien-Empera** [scaactk/PARA#3]
Excuse me, I'm not familar with matlab and failed in running this code. So I would like to ask some questions.

my goal is to implement Ripley K function and DBSCAN of TCRs.

1. i can't find'File .\Test dataset\coordinates.txt' in 'Test dataset'. There are only '1.txt' and 'test4.txt'.
2. how to choose the ROI? I click the Rectangular border and there will be 'aaa = 1x1 cell  {0x0 double} ', and a 'corrdinate.txt' will appear in 'Test.dataset'.
3.  i try to load the new 'corrdinate.txt'  from step 2 to the button 'select coordinates file', then click 'Add ROI'---click 'RipleyK Test', then see error. 
>> ClusDoC

aaa =

  1×1 cell 数组

    {0×0 double}

Ripley K test on Selected ROI
Ripley K test exited with errors
索引超出数组范围。

出错 RipleyKFun (line 15)
    xcenter = x(:,1)-xmin(1);

出错 ClusDoC>RipleyKtest (line 2020)
            [handles.RipleyK.r(:,1), handles.RipleyK.Lr_r(:,1)] = RipleyKFun( xCh1, handles.RipleyK.Area, ...
 
错误使用 uiwait (line 81)
计算 UIControl Callback 时出错。
Thank you.

(您好，我不太熟悉matlab，目前想实现一下TCR聚类分析，想请教一些问题：
1. 按照您所写，我上传了相应文件，但找不到coordinates.txt，GUI的第二栏（select coordinates file）该上传什么文件呢？
2. 如何选择ROI？我用矩形工具框选之后只会出现一个1x1 cell，并分析报错，如图，希望得到指正)

**Comment by scaactk** [comment]
Hi [Alien],
The code for matlab is not developed by me, and I just did some secondary development on it. It is a complex framework, but i can still give some guidance for using. After open GUI, you can choose to the input with certain format, and then you need to select the output folder, as for the coordinates part is not necessary for an choose, you can draw it my mouse. After drawing, don't forget to double click it. Hope this can help you.
